load('drv_test_dt.mat')
for i = 1:size(drv_test_dt,1)
    mount_driver(i) = struct("time",drv_test_dt(i,1),... ...
        "mount_drv_po",drv_test_dt(i,2:15),...
        "mount_cmd",drv_test_dt(i,16:18),...
        "mount_t",drv_test_dt(i,19:34));
end
 save("mount_driver_test","mount_driver")